### ISSUE TITLE
Local variable 'path' referenced before assignment

### ISSUE THREAD

**Issue by jasich** [jacebrowning/gdm#57]
```
gdm uninstall --quiet
Traceback (most recent call last):
  File "/usr/local/bin/gdm", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/gdm/cli.py", line 98, in main
    success = function(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/gdm/commands.py", line 82, in delete
    for _ in config.get_deps(allow_dirty=force):
  File "/usr/local/lib/python3.4/site-packages/gdm/config.py", line 211, in get_deps
    yield source.identify(allow_dirty=allow_dirty)
  File "/usr/local/lib/python3.4/site-packages/gdm/config.py", line 109, in identify
    return path, "<missing>", "<unknown>"
UnboundLocalError: local variable 'path' referenced before assignment
```

**Comment by jacebrowning** [comment]
Thanks for the report! What is the output of `gdm --version`?

**Comment by jasich** [comment]
`GDM v0.4`

**Comment by jacebrowning** [comment]
`$ pip3 install gdm>=0.4.2` should fix your issue.
